### ISSUE TITLE
Scale not working after entity got too small

### ISSUE THREAD

**Issue by ProfiBecher** [56738/EasyArmorStands#13]
I observed that if you get an entity to a scale of 0.0 the plugin isn't able to rescale the entity by using the given item tool during scale mode. 
Most likely because scaling is achieved by multiplying the existing value by something?

It also spams your logs with the following messages when trying to scale the entity:
```log
[13:06:42] [Server thread/WARN]: [EasyArmorStands] Task #39 for EasyArmorStands v2.1.0 generated an exception
java.lang.IllegalArgumentException: x not finite
	at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.Location.checkFinite(Location.java:1080) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.entity.CraftEntity.teleport(CraftEntity.java:239) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at org.bukkit.craftbukkit.entity.CraftEntity.teleport(CraftEntity.java:232) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at org.bukkit.craftbukkit.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:741) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at org.bukkit.craftbukkit.entity.CraftEntity.teleport(CraftEntity.java:226) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at EasyArmorStands-2.1.0.jar/me.m56738.easyarmorstands.property.entity.EntityLocationProperty.setValue(EntityLocationProperty.java:29) ~[EasyArmorStands-2.1.0.jar:?]
	at EasyArmorStands-2.1.0.jar/me.m56738.easyarmorstands.property.entity.EntityLocationProperty.setValue(EntityLocationProperty.java:10) ~[EasyArmorStands-2.1.0.jar:?]
	at EasyArmorStands-2.1.0.jar/me.m56738.easyarmorstands.property.PermissionCheckedPropertyWrapper.setValue(PermissionCheckedPropertyWrapper.java:61) ~[EasyArmorStands-2.1.0.jar:?]
	at EasyArmorStands-2.1.0.jar/me.m56738.easyarmorstands.property.TrackedPropertyWrapper.setValue(TrackedPropertyWrapper.java:41) ~[EasyArmorStands-2.1.0.jar:?]
	at EasyArmorStands-2.1.0.jar/me.m56738.easyarmorstands.editor.tool.EntityScaleTool$SessionImpl.updatePosition(EntityScaleTool.java:69) ~[EasyArmorStands-2.1.0.jar:?]
	at EasyArmorStands-2.1.0.jar/me.m56738.easyarmorstands.editor.tool.EntityScaleTool$SessionImpl.setChange(EntityScaleTool.java:77) ~[EasyArmorStands-2.1.0.jar:?]
	at EasyArmorStands-2.1.0.jar/me.m56738.easyarmorstands.editor.node.ScaleToolNode.onUpdate(ScaleToolNode.java:80) ~[EasyArmorStands-2.1.0.jar:?]
	at EasyArmorStands-2.1.0.jar/me.m56738.easyarmorstands.session.SessionImpl.update(SessionImpl.java:205) ~[EasyArmorStands-2.1.0.jar:?]
	at EasyArmorStands-2.1.0.jar/me.m56738.easyarmorstands.session.SessionManagerImpl.update(SessionManagerImpl.java:67) ~[EasyArmorStands-2.1.0.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Noticed this issue on:
MC `v1.20.6 (Paper 1.20.6-124-master@0fcf3e3)`
Plugin `v2.1.0`

**Incredibly well made plugin btw.! Awesome work!**

**Comment by 56738** [comment]
Fixed in https://hangar.papermc.io/56738/EasyArmorStands/versions/2.1.1-SNAPSHOT+119. Thanks!
