### ISSUE TITLE
java.lang.IllegalArgumentException: Damage cannot be negative

### ISSUE THREAD

**Issue by Snabeldier** [56738/EasyArmorStands#23]
Hello :)

When starting my 1.20.6 Paper Server with EasyArmorStands 2.4.0 (also tested with 2.2.1) these errors appear in my console.
I already deleted the config-folder and restarted - same errors appeared.

Is there anything I can do?

<strong>Errors:</strong>
```
[19:56:20] [Server thread/INFO]: [EasyArmorStands] Enabling EasyArmorStands v2.4.0
[19:56:21] [Server thread/ERROR]: [EasyArmorStands] Failed to load property easyarmorstands:armor_stand/base_plate
java.lang.IllegalArgumentException: Damage cannot be negative
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.inventory.CraftMetaItem.setDamage(CraftMetaItem.java:1554) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at org.bukkit.inventory.ItemStack.setDurability(ItemStack.java:259) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:99) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:76) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.config.serializer.ItemTemplateSerializer.deserialize(ItemTemplateSerializer.java:43) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.config.serializer.ItemTemplateSerializer.deserialize(ItemTemplateSerializer.java:21) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.lib.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.lib.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.property.type.ConfigurablePropertyType.load(ConfigurablePropertyType.java:46) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.property.type.BooleanPropertyType.load(BooleanPropertyType.java:19) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.property.type.PropertyTypeRegistryImpl.load(PropertyTypeRegistryImpl.java:47) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.property.type.PropertyTypeRegistryImpl.load(PropertyTypeRegistryImpl.java:37) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin$2.apply(EasyArmorStandsPlugin.java:450) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin.loadMergedConfig(EasyArmorStandsPlugin.java:594) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin.loadConfig(EasyArmorStandsPlugin.java:457) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin.loadProperties(EasyArmorStandsPlugin.java:442) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin.onEnable(EasyArmorStandsPlugin.java:227) ~[EasyArmorStands-2.4.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:56:21] [Server thread/ERROR]: [EasyArmorStands] Failed to load property easyarmorstands:armor_stand/lock
java.lang.IllegalArgumentException: Damage cannot be negative
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.inventory.CraftMetaItem.setDamage(CraftMetaItem.java:1554) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at org.bukkit.inventory.ItemStack.setDurability(ItemStack.java:259) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:99) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:76) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.config.serializer.ItemTemplateSerializer.deserialize(ItemTemplateSerializer.java:43) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.config.serializer.ItemTemplateSerializer.deserialize(ItemTemplateSerializer.java:21) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.lib.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.lib.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.property.type.ConfigurablePropertyType.load(ConfigurablePropertyType.java:46) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.property.type.BooleanPropertyType.load(BooleanPropertyType.java:19) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.property.type.PropertyTypeRegistryImpl.load(PropertyTypeRegistryImpl.java:47) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.property.type.PropertyTypeRegistryImpl.load(PropertyTypeRegistryImpl.java:37) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin$2.apply(EasyArmorStandsPlugin.java:450) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin.loadMergedConfig(EasyArmorStandsPlugin.java:594) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin.loadConfig(EasyArmorStandsPlugin.java:457) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin.loadProperties(EasyArmorStandsPlugin.java:442) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin.onEnable(EasyArmorStandsPlugin.java:227) ~[EasyArmorStands-2.4.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:56:21] [Server thread/ERROR]: [EasyArmorStands] Failed to load property easyarmorstands:armor_stand/marker
java.lang.IllegalArgumentException: Damage cannot be negative
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.inventory.CraftMetaItem.setDamage(CraftMetaItem.java:1554) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at org.bukkit.inventory.ItemStack.setDurability(ItemStack.java:259) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:99) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:76) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.config.serializer.ItemTemplateSerializer.deserialize(ItemTemplateSerializer.java:43) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.config.serializer.ItemTemplateSerializer.deserialize(ItemTemplateSerializer.java:21) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.lib.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.lib.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.property.type.ConfigurablePropertyType.load(ConfigurablePropertyType.java:46) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.property.type.BooleanPropertyType.load(BooleanPropertyType.java:19) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.property.type.PropertyTypeRegistryImpl.load(PropertyTypeRegistryImpl.java:47) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.property.type.PropertyTypeRegistryImpl.load(PropertyTypeRegistryImpl.java:37) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin$2.apply(EasyArmorStandsPlugin.java:450) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin.loadMergedConfig(EasyArmorStandsPlugin.java:594) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin.loadConfig(EasyArmorStandsPlugin.java:457) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin.loadProperties(EasyArmorStandsPlugin.java:442) ~[EasyArmorStands-2.4.0.jar:?]
	at EasyArmorStands-2.4.0.jar/me.m56738.easyarmorstands.EasyArmorStandsPlugin.onEnable(EasyArmorStandsPlugin.java:227) ~[EasyArmorStands-2.4.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:626) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:575) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-151-a4f0f5c]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by 56738** [comment]
Fixed in v2.4.1. https://hangar.papermc.io/56738/EasyArmorStands/versions

Thanks!
