### ISSUE TITLE
dubble click register

### ISSUE THREAD

**Issue by Brammie260** [56738/EasyArmorStands#8]
Hey, I am experiencing a very interesting bug. When I want to edit the item display through the wall it comes right on if I double click and yet I only click once. Once you want to move something and then want to move other axes for example I sometimes have to click 10 times before I can click new axe again.

and sometimes its working like it needs to work.. strange

Edit: I see that i have this issue when a block is in my path. Like if there is air at my crossing there is no problem (until now)

Example in video.

Used the latest version, here I experienced the problem and if I go back two versions I still experience it too.

[https://youtu.be/S_k4azyheo8](url)

**Comment by Brammie260** [comment]
and sometimes its working like it needs to work.. strange

**Comment by 56738** [comment]
Can you send the output of `/eas debug`? That contains some important things like the server version.

**Comment by Brammie260** [comment]
![2023-11-04_19 19 16](https://github.com/56738/EasyArmorStands/assets/16277770/1a2c1a07-9576-498e-a1b1-9020e0ecee5f)

**Comment by 56738** [comment]
Please try with this .jar file: https://hangar.papermc.io/56738/EasyArmorStands/versions/2.0.3-SNAPSHOT+95

It disables detecting arm swings as left-clicks (08372dbbba81f0234fdb89f2dffa48d2536a776c).

**Comment by Brammie260** [comment]
sorry for late anwser but i don't have commands. Plugin is enabled but is i do /help easyarmorstands there are no commands and i can't do the commands

**Comment by 56738** [comment]
Are there any errors in the console?

**Comment by Brammie260** [comment]
[19:05:32] [Server thread/ERROR]: java.lang.ClassCastException: Cannot cast org.bukkit.entity.EntityType to net.kyori.adventure.translation.Translatable initializing EasyArmorStands v2.0.3-SNAPSHOT (Is it up to date?)
java.lang.RuntimeException: java.lang.ClassCastException: Cannot cast org.bukkit.entity.EntityType to net.kyori.adventure.translation.Translatable
        at me.m56738.easyarmorstands.capability.entitytype.v1_18_paper.EntityTypeCapabilityProvider$EntityTypeCapabilityImpl.getName(EntityTypeCapabilityProvider.java:53) ~[?:?]
        at me.m56738.easyarmorstands.element.SimpleEntityElementType.<init>(SimpleEntityElementType.java:33) ~[?:?]
        at me.m56738.easyarmorstands.element.ArmorStandElementType.<init>(ArmorStandElementType.java:11) ~[?:?]
        at me.m56738.easyarmorstands.EasyArmorStandsPlugin.onLoad(EasyArmorStandsPlugin.java:146) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:440) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: Cannot cast org.bukkit.entity.EntityType to net.kyori.adventure.translation.Translatable
        at java.lang.Class.cast(Class.java:3889) ~[?:?]
        at me.m56738.easyarmorstands.capability.entitytype.v1_18_paper.EntityTypeCapabilityProvider$EntityTypeCapabilityImpl.getName(EntityTypeCapabilityProvider.java:51) ~[?:?]
        ... 8 more


Plugin is enabled but there are no commands you can use.

**Comment by 56738** [comment]
Seems like EasyArmorStands incorrectly assumed you were using Paper.

Here's a new .jar file which should fix that: https://hangar.papermc.io/56738/EasyArmorStands/versions/2.0.3-SNAPSHOT+98

**Comment by Brammie260** [comment]
I've tried alot and its working like it need to do! Sorry for late reaction
